---
- hosts: SS_TEAM
  sudo: yes

  # vars_files:
  #   - vars/...
  #
  # vars:
  #   wp_version: ...

  tasks:
    - name: Check Breakfix Location
      file: path=/home/Breakfix state=absent

    - name: Transfer zip File
      copy: src:'Breakfixes.zip' dest:'/home/'

    - name: Unzip File
      unarchive: src='/home/Breakfixes.zip' dest='/home/Breakfix' copy=no
